# Generated by Django 4.2.2 on 2023-06-16 11:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('prodhouse', '0003_portfolio_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('message', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='image/slave/')),
            ],
        ),
    ]
