# Generated by Django 4.2.2 on 2023-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodhouse', '0004_slave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slave',
            name='message',
        ),
    ]
