# Generated by Django 4.2.2 on 2023-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodhouse', '0005_remove_slave_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='detail',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='role',
            field=models.CharField(default='', max_length=300),
        ),
    ]
