# Generated by Django 4.2.2 on 2023-07-10 08:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('prodhouse', '0006_slave_detail_slave_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='GDrive',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='bio',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='exp',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='fb_id',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='imdb_id',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='insta_id',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='linkedin_url',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='slave_type',
            field=models.CharField(choices=[('Core', 'Core Members'), ('Employee', 'Employees'), ('Creatives', 'Creative members')], default='Employee', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
